apiVersion: v1
kind: ConfigMap
metadata:
  name: back-config
  namespace: b-ns
data:
  PORT: "8000"
  GUESTBOOK_DB_ADDR: db-svc.d-ns.svc.cluster.local:27017
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: back
  namespace: b-ns
spec:
  replicas: 3
  selector:
    matchLabels:
      tier: backend
  template:
    metadata:
      labels:
        tier: backend
    spec:
      containers:
        - image: wooosik/agoraback:1.0
        name: back
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: back-config
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: back-svc
  namespace: b-ns
spec:
  ports:
  - port: 8000
    protocol: TCP
    nodePort: 32323
  selector:
    tier: backend
  type: NodePort

