version: '3.8'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile 
    ports:
      - "8080:8080"
    networks:
      - frontend-network
    depends_on:
      - backend
    restart: always

  backend:
    ports:
        - "8000:8000"
    environment:
      PORT: 8000
      GUESTBOOK_DB_ADDR: mongodb:27017
    networks:
      - backend-network
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - mongodb
    restart: always

  mongodb:
    ports:
      - "17017:27017"
    image:
      mongo:4
    volumes:
      - /home/student/AGORA-Mk2/DevDB:/data/db
    networks:
      - backend-network
    restart: always

networks:
  frontend-network: 
    ipam:
        driver: default
        config:
          - subnet: 172.28.0.0/16
  backend-network:
    ipam:
        driver: default
        config:
          - subnet: 172.29.0.0/16